version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`www.sitchat.ai`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.services.backend.loadbalancer.server.port=5001"
    ports:
      - "5001:5001"
    environment:
      - FLASK_DEBUG=false
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-for-socket-io}
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "https://www.sitchat.ai/v1"
    container_name: vue-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8081:80"
    environment:
      - VITE_API_URL=https://www.sitchat.ai/v1
    depends_on:
      - backend
    restart: unless-stopped