version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-backend
    ports:
      - "5001:5001"
    environment:
      - FLASK_DEBUG=false
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-for-socket-io}
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8081:80"
    environment:
      - VITE_API_URL=/api
    depends_on:
      - backend
    restart: unless-stopped